### ISSUE TITLE
sys-devel/llvm-11.1.0: FAILED: lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUPropagateAttributes.cpp.o

### ISSUE THREAD

**Issue by HougeLangley** [xen0n/loongson-overlay#11] opened 2022-02-09 14:39 UTC
```
[903/2885] /usr/bin/loongarch64-unknown-linux-gnu-g++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/var/tmp/portage/sys-devel/llvm-11.1.0/work/llvm-11.1.0_build-.lp64d/lib/Target/AMDGPU -I/var/tmp/portage/sys-devel/llvm-11.1.0/work/llvm/lib/Target/AMDGPU -I/var/tmp/portage/sys-devel/llvm-11.1.0/work/llvm-11.1.0_build-.lp64d/include -I/var/tmp/portage/sys-devel/llvm-11.1.0/work/llvm/include  -DNDEBUG -O2 -pipe -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -fvisibility=hidden -std=c++14 -MD -MT lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUPropagateAttributes.cpp.o -MF lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUPropagateAttributes.cpp.o.d -o lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUPropagateAttributes.cpp.o -c /var/tmp/portage/sys-devel/llvm-11.1.0/work/llvm/lib/Target/AMDGPU/AMDGPUPropagateAttributes.cpp
FAILED: lib/Target/AMDGPU/CMakeFiles/LLVMAMDGPUCodeGen.dir/AMDGPUPropagateAttributes.cpp.o
```

emerge full build log: 
[loongarch_sys-devel_llvm_11_1_full.zip](https://github.com/xen0n/loongson-overlay/files/8033523/loongarch_sys-devel_llvm_11_1_full.zip)

```
~ emerge --info '=sys-devel/llvm-11.1.0::loongson'
setlocale: unsupported locale setting
setlocale: unsupported locale setting
Portage 3.0.30 (python 3.9.10-final-0, targets/systemd, gcc-12.0.1, glibc-2.35, 5.17.0-rc1 loongarch64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.17.0-rc1-loongarch64-with-glibc2.35
KiB Mem:    16571088 total,  13315168 free
KiB Swap:    4027696 total,   4027696 free
Head commit of repository gentoo: 48449a998c95f8f33a35d8b4d0e4fd1a7fa8f958

Head commit of repository cutefishos: 889a214d4a17386efb1241767bd7d88773976684

Head commit of repository loongson: 12a5c5fca4b02db448f81030d594abd55a013699

sh bash 5.1_p16
ld GNU ld (Gentoo 2.37_p1 p2) 2.37
app-misc/pax-utils:        1.3.3::loongson
app-shells/bash:           5.1_p16::gentoo
dev-lang/perl:             5.34.0-r6::loongson
dev-lang/python:           2.7.18_p13::gentoo, 3.9.10-r1::gentoo, 3.10.2-r1::gentoo
dev-util/cmake:            3.22.2::gentoo
dev-util/meson:            0.60.3::gentoo
sys-apps/baselayout:       2.8::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-apps/systemd:          9999::gentoo
sys-devel/autoconf:        2.13-r1::gentoo, 2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.37_p1-r3::loongson
sys-devel/binutils-config: 5.4::gentoo
sys-devel/gcc:             12.0.0_pre9999::loongson
sys-devel/gcc-config:      2.5-r1::gentoo
sys-devel/libtool:         2.4.6-r6::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.17_rc2_p20220124::loongson (virtual/os-headers)
sys-libs/glibc:            2.35::loongson
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: git
    sync-uri: https://github.com/gentoo/gentoo.git
    priority: -1000

cutefishos
    location: /var/db/repos/cutefishos
    sync-type: git
    sync-uri: https://github.com/HougeLangley/cutefishos-overlay.git
    masters: gentoo

loongson
    location: /var/db/repos/loogson
    sync-type: git
    sync-uri: https://github.com/xen0n/loongson-overlay
    masters: gentoo

ACCEPT_KEYWORDS="loong ~loong"
ACCEPT_LICENSE="*"
CBUILD="loongarch64-unknown-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="loongarch64-unknown-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--with-bdeps=y --autounmask-write=y --quiet-build=y --jobs=1 -l"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo/"
LANG="C.UTF8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="en_US zh_CN en zh"
MAKEOPTS="-j4"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X acl bzip2 cli crypt dri fortran gdbm iconv ipv6 libglvnd loong ncurses nls nptl openmp pam pcre readline seccomp split-usr ssl systemd udev unicode wayland xattr zlib" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput evdev" KERNEL="linux" L10N="en-US zh-CN en zh" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS
```

```
emerge -pqv '=sys-devel/llvm-11.1.0::loongson'  
setlocale: unsupported locale setting
setlocale: unsupported locale setting
[ebuild  N    ] sys-devel/llvm-11.1.0  USE="gold libffi ncurses -debug -doc -exegesis -libedit -test -xar -xml -z3" LLVM_TARGETS="(AArch64) (AMDGPU) (ARM) (AVR) (BPF) (Hexagon) (Lanai) (LoongArch) (MSP430) (Mips) (NVPTX) (PowerPC) (RISCV) (Sparc) (SystemZ) (WebAssembly) (X86) (XCore) (-ARC) (-VE)" 
[ebuild  N    ] sys-devel/llvmgold-11
```

**Comment by xen0n** [comment] 2022-02-09 15:03
duplicate of #4 which is caused by https://github.com/loongson/gcc/issues/77

**Closed as completed by xen0n** 2022-02-09 15:03 UTC
Labels: duplicate
